In [10]:
# PyTorch - 2

# Autograd

In [11]:
import torch

In [12]:
# example 1 : calculating gradient

x = torch.tensor(3.0,requires_grad=True)

# requires_grad = True : mandatory

In [13]:
y = x**2

print(y)

y.backward()

print(x.grad)

tensor(9., grad_fn=<PowBackward0>)
tensor(6.)


In [15]:
# ex : 2

a = torch.tensor(4.0,requires_grad=True)

b = a**2

c = torch.sin(b)

c.backward()              # dc/da = dc/db . db/da

print(a.grad)

tensor(-7.6613)


In [20]:
# ex : 3 with vector input

x = torch.tensor([1.0,2.0,3.0],requires_grad=True)    # x = x1,x2,x3

y = (x**2).mean()       # applying mean() fn : y = fn(x1,x2,x3)

y.backward()            # Dy = [dy/dx1 ,dy/dx2, dy/dx3]

print(x.grad)

tensor([0.6667, 1.3333, 2.0000])


In [22]:
# clearing grads

# if we dont clear gradients they start accumalating everytime we call backward()
# NEED TO DO it AFTER EVERY EPOCH

x.grad.zero_()

tensor([0., 0., 0.])

In [26]:
# disabling gradient tracking

# once NN is trained , we dont need backward() to predict
# need to disable it as it takes memory

x.requires_grad_(False)

# y.backward() gives ERROR

tensor([1., 2., 3.])

In [28]:
# way 2

with torch.no_grad():
    y = x**2
   #  y.backward()        # ERROR

