In [1]:
# PyTorch - 1

# Basics

In [2]:
import torch

In [3]:
# check version

torch.__version__

'2.9.0+cu126'

In [4]:
# GPU availability

if torch.cuda.is_available():
  print(torch.cuda.get_device_name())
else :
  print("no GPU available")

Tesla T4


In [5]:
# Turn on available GPU (Google Colab)

# tools bar >> Runtime >> Change runtime type >> select T4 GPU

In [6]:
# using GPU

device = torch.device("cuda")

t= torch.empty((3,3),device=device)

t


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [7]:
from math import e
# Create tensors

# empty
a = torch.empty(2,3)        # but has exsisting values at that address (if any)

# all zeros
b = torch.zeros(2,3)

# all ones
c = torch.ones(2,3)

# identical
d = torch.eye(3,3)           # diagonal elements 1

# full
e = torch.full((2,3),3)       # 2x3 matrix with all values as 3

print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[3, 3, 3],
        [3, 3, 3]])


In [8]:
# generating random tensors

f = torch.rand(2,3)              # between 0-10

# random ints
g = torch.randint(1,10,(2,3))    # between 1-10 , 2x3 matrix

# with seed
torch.manual_seed(42)            # same values everytime when seed = 42
h = torch.rand(2,3)


print(f)
print(g)
print(h)

tensor([[0.3415, 0.7300, 0.8675],
        [0.9754, 0.5538, 0.0049]])
tensor([[1, 2, 1],
        [5, 8, 7]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [9]:
# using arange
i = torch.arange(11,20,2)      # rank 1 tensor between 11-20 with step = 2

# using linspace
j = torch.linspace(11,20,12)   # 12 elements linear spaced between 11-20

print(i)
print(j)

tensor([11, 13, 15, 17, 19])
tensor([11.0000, 11.8182, 12.6364, 13.4545, 14.2727, 15.0909, 15.9091, 16.7273,
        17.5455, 18.3636, 19.1818, 20.0000])


In [10]:
# creating tensors manually

t1 = torch.tensor([[3,2,1],[9,6,3],[1,1,1]])
t1

tensor([[3, 2, 1],
        [9, 6, 3],
        [1, 1, 1]])

In [11]:
# basic info

print(id(t1))        # memory address

print(type(t1))      # class

print(t1.shape)      # shape

print(t1.dtype)      # data type

print(t1.device)     # cpu / gpu / tpu

132320526856704
<class 'torch.Tensor'>
torch.Size([3, 3])
torch.int64
cpu


In [19]:
# change dtype

print(t1.dtype)

t1 = t1.to(torch.float32)

print(t1.dtype)

torch.int64
torch.float32


In [21]:
# generating LIKEs
# same shape LIKEs

print(torch.empty_like(t1))

print(torch.zeros_like(t1))

print(torch.ones_like(t1))

print(torch.rand_like(t1))

tensor([[1.4163e+19, 4.3171e-41, 3.0561e-02],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])


In [13]:
# cloning / copying

t2 = t1.clone()

t2

tensor([[3, 2, 1],
        [9, 6, 3],
        [1, 1, 1]])

In [31]:
# reshaping

print(t1.reshape(1,3,3))    # 2D to 3D

print(torch.flatten(t1))         # to 1D

print(torch.squeeze(t1,dim=0))    # remove dimensions  ; here 3D to 2D

print(torch.unsqueeze(t1,dim=0))  # adds 'FAKE' dimensions ; here 3D to 4D

tensor([[[3., 2., 1.],
         [9., 6., 3.],
         [1., 1., 1.]]])
tensor([3., 2., 1., 9., 6., 3., 1., 1., 1.])
tensor([[3., 2., 1.],
        [9., 6., 3.],
        [1., 1., 1.]])
tensor([[[[3., 2., 1.],
          [9., 6., 3.],
          [1., 1., 1.]]]])


In [32]:
# applying activation fns

print(torch.sigmoid(t1))

print(torch.tanh(t1))

print(torch.relu(t1))

tensor([[[0.9526, 0.8808, 0.7311],
         [0.9999, 0.9975, 0.9526],
         [0.7311, 0.7311, 0.7311]]])
tensor([[[0.9951, 0.9640, 0.7616],
         [1.0000, 1.0000, 0.9951],
         [0.7616, 0.7616, 0.7616]]])
tensor([[[3., 2., 1.],
         [9., 6., 3.],
         [1., 1., 1.]]])


In [35]:
# numpy to tensor

import numpy as np

a = np.arange(20,30,5)

print(type(a))

b = torch.from_numpy(a)

print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
